name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-15

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v5

      - name: Instalar bash@5 e bats
        run: |
          brew install bash bats-core

      - name: Detectar caminho do bash@5
        id: bash
        run: echo "bash_path=$(brew --prefix)/bin/bash" >> "$GITHUB_OUTPUT"

      - name: Verificar versão do Bash
        run: ${{ steps.bash.outputs.bash_path }} --version

      - name: Rodar testes com Bats e Bash 5
        run: |
          ${{ steps.bash.outputs.bash_path }} -c 'bats ./test/test_requirements.bats'
